[build]
  functions = "api"

[functions]
  external_node_modules = ["express", "mongodb", "body-parser"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true